### ISSUE TITLE
issue with the arrow keys 

### ISSUE THREAD

**Issue by rajkumarks7** [eiannone/keyboard#20]
when ever i press any arrow key i am getting the error as panic: runtime error: index out of range [3] with length 3
goroutine 22 [running]:
github.com/eiannone/keyboard.extract_event(0xc0000a4080, 0x3, 0x80, 0x1, 0x6600000001, 0x0, 0x0)
        /home/karthik/go/src/github.com/eiannone/keyboard/keyboard.go:68 +0x1ba
github.com/eiannone/keyboard.inputEventsProducer()
        /home/karthik/go/src/github.com/eiannone/keyboard/keyboard.go:107 +0x7f
created by github.com/eiannone/keyboard.initConsole
        /home/karthik/go/src/github.com/eiannone/keyboard/keyboard.go:197 +0x3de

Process finished with exit code 2

**Comment by eiannone** [comment]
Hi @rajkumarks7 , which terminal are you using? Could you please tell me the output of `echo $TERM` command?

**Comment by rajkumarks7** [comment]
xterm-256color
I got this code when i ran that command .

**Comment by eiannone** [comment]
Ok, should be fixed with latests commits 5797b640fd6d5e528d44c4f382c33be677c1c0c2 and caf4b762e807eee1398b6400b0288594bb963ffb.
There was a typo, plus it seemed that reading escape sequences for special keys from terminfo files was not so reliable, so I switched to builtin mappings whenever possible.

Please pull latest version and check if it's working correctly now.

**Comment by rajkumarks7** [comment]
thank you very much the issue got resolved. sir can you make this work behind the screen, i mean like not on terminal like when ever you press a key outside terminal or in other apps it should show like that . it is not showing any keys for the shift,alt,caplock , ctrl ,fn and windows key.if you can make it work behind the terminal it will awesome please tell me.
